# Generated by Django 5.1.4 on 2024-12-27 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Computer', models.CharField(blank=True, max_length=100)),
                ('Math', models.CharField(blank=True, max_length=100)),
                ('Physics', models.CharField(blank=True, max_length=100)),
                ('Chemistry', models.CharField(blank=True, max_length=100)),
                ('Biology', models.CharField(blank=True, max_length=100)),
                ('English', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Profile', models.ImageField(blank=True, upload_to='profile')),
                ('roll_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
