# Generated by Django 5.1.4 on 2024-12-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Biology',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Chemistry',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Computer',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='English',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Math',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Physics',
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
