# Generated by Django 5.1.4 on 2024-12-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_subject_student_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject1',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject2',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject3',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject4',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject5',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject6',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
            preserve_default=False,
        ),
    ]
