# Generated by Django 5.1.4 on 2024-12-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_subject_name_subject_subject1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject6',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(auto_created=True),
        ),
    ]
