# Generated by Django 5.1.4 on 2024-12-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subject_subject2_remove_subject_subject3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True),
        ),
    ]
